apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: homework
  name: homework
  resourceVersion: "50726"
  uid: 6d59ba02-8a1e-44e0-86cd-c8fe679ddff0
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
