apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: homework
spec:
  containers:
  - name: web
    image: nginx
    volumeMounts:
    - name: homework-volume
      mountPath: /homework
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "Hello, World!" > /init/index.html']
    volumeMounts:
    - name: homework-volume
      mountPath: /init
  volumes:
  - name: homework-volume
    emptyDir: {}